# Generated by Django 5.2.6 on 2025-09-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobtaskhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobTaskHistory',
        ),
    ]
