# Generated by Django 5.2.6 on 2025-09-27 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_user_is_staff_remove_user_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('eq_type', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['eq_type', 'name'],
                'indexes': [models.Index(fields=['eq_type'], name='idx_equipment_type'), models.Index(fields=['is_active'], name='idx_equipment_active'), models.Index(fields=['serial_number'], name='idx_equipment_serial')],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('client_name', models.CharField(max_length=255)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(limit_choices_to={'role': 'TECHNICIAN'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
            options={
                'ordering': ['job', 'order'],
            },
        ),
        migrations.CreateModel(
            name='JobTaskEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='jobs.equipment')),
                ('job_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobtask')),
            ],
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='idx_jobs_status'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['priority'], name='idx_jobs_priority'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['scheduled_date'], name='idx_jobs_scheduled_date'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['assigned_to', 'status'], name='idx_jobs_assigned_status'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['created_by'], name='idx_jobs_created_by'),
        ),
        migrations.AddIndex(
            model_name='jobtask',
            index=models.Index(fields=['job', 'status'], name='jobs_jobtas_job_id_e81a86_idx'),
        ),
        migrations.AddIndex(
            model_name='jobtask',
            index=models.Index(fields=['job', 'order'], name='jobs_jobtas_job_id_c8a79b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobtask',
            unique_together={('job', 'order')},
        ),
        migrations.AddIndex(
            model_name='jobtaskequipment',
            index=models.Index(fields=['job_task'], name='idx_jte_task_id'),
        ),
        migrations.AddIndex(
            model_name='jobtaskequipment',
            index=models.Index(fields=['equipment'], name='idx_jte_equipment_id'),
        ),
        migrations.AlterUniqueTogether(
            name='jobtaskequipment',
            unique_together={('job_task', 'equipment')},
        ),
    ]
