# Generated by Django 5.2.6 on 2025-09-27 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_equipment_job_jobtask_jobtaskequipment_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jobtask',
            new_name='job_task_job_id_edfd28_idx',
            old_name='jobs_jobtas_job_id_e81a86_idx',
        ),
        migrations.RenameIndex(
            model_name='jobtask',
            new_name='job_task_job_id_8f8809_idx',
            old_name='jobs_jobtas_job_id_c8a79b_idx',
        ),
        migrations.AlterModelTable(
            name='equipment',
            table='equipment',
        ),
        migrations.AlterModelTable(
            name='job',
            table='job',
        ),
        migrations.AlterModelTable(
            name='jobtask',
            table='job_task',
        ),
        migrations.AlterModelTable(
            name='jobtaskequipment',
            table='job_task_equipment',
        ),
    ]
