# Generated by Django 5.2.6 on 2025-10-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_delete_jobtaskhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='overdue',
            field=models.BooleanField(default=False),
        ),
    ]
